CREATE SEQUENCE IF NOT EXISTS upwork.upwork_jobs_id_seq
    START WITH 1
    INCREMENT BY 1;

ALTER SEQUENCE upwork.upwork_jobs_id_seq
    OWNER TO n8n;

CREATE TABLE IF NOT EXISTS upwork.upwork_jobs
(
    id bigint NOT NULL DEFAULT nextval('upwork.upwork_jobs_id_seq'::regclass),
    job_id text NOT NULL,
    url text,
    canonical_url text,
    title text,
    category text,
    subcategory text,
    description text,
    summary text,
    job_type text,
    fixed_price numeric,
    hourly_min numeric,
    hourly_max numeric,
    hourly_raw text,
    duration text,
    weekly_hours text,
    experience_level text,
    posted_time text,
    contract_to_hire boolean,
    project_type text,
    location_raw text,
    location_country text,
    location_region text,
    location_worldwide boolean,
    location_remote boolean,
    client_country text,
    client_timezone_or_city text,
    client_payment_verified boolean,
    client_rating numeric,
    client_reviews_count integer,
    client_total_spent text,
    client_hires integer,
    client_active_hires integer,
    client_total_hours text,
    client_company_size text,
    client_industry text,
    client_member_since text,
    proposals text,
    last_viewed_by_client text,
    interviewing integer,
    invites_sent integer,
    unanswered_invites integer,
    last_activity text,
    skills jsonb,
    requirement_tools jsonb,
    requirement_languages jsonb,
    requirement_frameworks jsonb,
    requirement_models jsonb,
    requirement_databases jsonb,
    requirement_soft_skills jsonb,
    requirement_certifications jsonb,
    custom_instruction text,
    ai_allowed boolean,
    long_term boolean,
    urgent boolean,
    scraper_source text,
    scraper_version text,
    page_title text,
    text_length integer,
    saved_file text,
    scraped_at timestamptz,
    validation_valid boolean,
    validation_errors jsonb,
    raw_json jsonb NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    analysis_input_hash text,
    stage2_processed_hash text,
    stage2_processed_at timestamptz,
    stage2_analysis_version text,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    last_changed_at timestamptz NOT NULL DEFAULT now(),
    seen_count bigint NOT NULL DEFAULT 1,
    CONSTRAINT upwork_jobs_pkey PRIMARY KEY (id),
    CONSTRAINT upwork_jobs_job_id_key UNIQUE (job_id)
);

ALTER TABLE upwork.upwork_jobs
    OWNER TO n8n;
